### ISSUE TITLE
Registration fails when no SMTP is configured.

### ISSUE THREAD

**Issue by bwulff** [sproutlabs/learninglocker-docker#1]
I'm running this image but did not configure any of the SMTP env vars. When I register an account in the first screen I get the following error that seems to have to do with the fact the an SMTP config is missing:

Swift_TransportException
Expected response code 250 but got code "", with message ""

(…/­vendor/­swiftmailer/­swiftmailer/­lib/­classes/­Swift/­Transport/­AbstractSmtpTransport.php383)

Is there a way to run the image without SMTP being configured?

**Comment by bwulff** [comment]
Tried to set env var SMTP_TO_LOG=true. But that had no effect.

**Comment by bwulff** [comment]
Solved it: I edited https://github.com/sproutlabs/learninglocker-docker/blob/master/docker-entrypoint.sh#L128 so that `'pretend' ==> true`. This makes the framework skip the part where it tries to send a mail.

**Comment by zpetterd** [comment]
Glad to hear you managed to resolve it. Do you reckon you would be able to create a pull request for your changes to slidewiki/learninglocker-docker ? I would be happy to merge it straight away
