### ISSUE TITLE
Using latest Learning Locker

### ISSUE THREAD

**Issue by ppounder** [sproutlabs/learninglocker-docker#4]
Learning Locker v2 is now using NodeJS not PHP. The DockerFile in here pulls down the latest so therefore this no longer works as it's set up for a PHP environment.

We have managed to get this working by replacing the following:

````
RUN curl -L -o learninglocker.tar.gz `curl -s https://api.github.com/repos/LearningLocker/learninglocker/releases/latest | jq --raw-output '.tarball_url'`\
	&& tar -xzf learninglocker.tar.gz -C /var/www/html --strip-components=1 \
	&& rm learninglocker.tar.gz \
	&& chown -R www-data /var/www/html
````
to this
````
RUN curl -L -o learninglocker.tar.gz `curl -s https://api.github.com/repos/LearningLocker/learninglocker/releases/5967511 | jq --raw-output '.tarball_url'`\
	&& tar -xzf learninglocker.tar.gz -C /var/www/html --strip-components=1 \
	&& rm learninglocker.tar.gz \
	&& chown -R www-data /var/www/html
````

So it uses the last v1 version (1.17 I believe).

Regards
Paul

**Comment by zpetterd** [comment]
Hi Paul,

I can put that update through. We are also working on the Docker config for
v2 but have run into some problems. It will be contributed back into the
main repo and hopefully published under a "learninglocker" organisation on
Docker hub. There will be a link here when it is ready

Zac

**Comment by sijpkes** [comment]
I'm currently attempting to run LL V2 in a docker container myself. Let me know if you need help with this project.

**Comment by halimj7** [comment]
I am a rookie so please be kind :). Is there a way to download an offline LL v2? Can anyone help please. Thanks.

**Comment by michzimny** [comment]
For LL v2 in docker you can have a look at my attempt: https://github.com/michzimny/learninglocker2-docker

**Comment by BrendanHalley** [comment]
This repo has now been depreciated due to the release of LL v2 and will receive no further updates.

If you're interested in setting up Learning Locker v2 with Docker I recommend the stack @michzimny has put together at https://github.com/michzimny/learninglocker2-docker
